### ISSUE TITLE
manifest_version should be 1

### ISSUE THREAD

**Issue by sousocheat** [Ulauncher/ulauncher-kill#1]
![screenshot from 2018-01-30 14-22-46](https://user-images.githubusercontent.com/34334156/35553128-28b2aa3a-05c9-11e8-84f8-4494a5721d96.png)

**Comment by gornostal** [comment]
Are you using latest Ulauncher app?

**Comment by gornostal** [comment]
please reopen if needed

**Comment by sousocheat** [comment]
I didn't use the latest version. Now that I've updated it, it's working fine. Thank you.
