### ISSUE TITLE
Typing kill results in just loading

### ISSUE THREAD

**Issue by rkunschke** [Ulauncher/ulauncher-kill#2]
Hi if i type kill ulauncher only shows loading... no matter if i type something more or not

**Comment by gornostal** [comment]
Could you run Ulauncher from command line like this `ulauncher -v` and post the logs?
You must stop Ulauncher app first.

**Comment by rkunschke** [comment]
```
[2018-02-04 00:29:30,304 pyinotify ERROR] add_watch: cannot watch /usr/share/wayland-protocols/unstable/idle-inhibit WD=-1, Errno=No space left on device (ENOSPC)
2018-02-04 00:29:30,304 | ERROR | pyinotify: add_watch() | add_watch: cannot watch /usr/share/wayland-protocols/unstable/idle-inhibit WD=-1, Errno=No space left on device (ENOSPC)
```
 it logs this while trying to load

**Comment by gornostal** [comment]
Sorry for the delay. Try this https://github.com/Ulauncher/Ulauncher/issues/51

**Comment by leinardi** [comment]
@rkunschke if you are  using a locale different than English, this PR could fix your issue: https://github.com/Ulauncher/ulauncher-kill/pull/3

If you want to test it just use this as source for the extension: https://github.com/leinardi/ulauncher-kill

**Comment by gornostal** [comment]
@leinardi thanks for the PR.

**Comment by leinardi** [comment]
@gornostal Thanks for the awesome launcher, I just switched after using Synapse for many years :+1:

**Comment by leinardi** [comment]
@gornostal I had a regression with https://github.com/Ulauncher/ulauncher-kill/commit/e216c435b616ca4643fde0c9616edd24ec3a2cc9#diff-5bc02cefb3ea9e27f1a6776eabd1935dR119

**Comment by gornostal** [comment]
@leinardi my mistake. Fixed now.
