### ISSUE TITLE
Enhancement: How about using Faenza icon set?

### ISSUE THREAD

**Issue by leinardi** [Ulauncher/ulauncher-kill#4]
This is just a suggestion: why not using Faenza icon set for the executable and main icon?

For example I would suggest these icons:

![application-x-executable](https://user-images.githubusercontent.com/273338/36356150-ea0f6938-14ed-11e8-8bc9-072aed7b527a.png) ![gtk-execute](https://user-images.githubusercontent.com/273338/36356157-fda1803a-14ed-11e8-9732-6215b3806792.png)
![exit](https://user-images.githubusercontent.com/273338/36356167-1e19a7f2-14ee-11e8-9d45-6ef3c39851fd.png) ![process-stop](https://user-images.githubusercontent.com/273338/36356175-30bb0806-14ee-11e8-90a7-f52054e37ce1.png)

This icon set is GPL licensed and is already part of some distribution iirc: https://tiheum.deviantart.com/art/Faenza-Icons-173323228

**Comment by gornostal** [comment]
Thanks for the suggestion, but I will keep existing icons for now.
To be consistent with Ulauncher icons, this extension uses the same icon for executables.
