### ISSUE TITLE
Question: howto use it ?

### ISSUE THREAD

**Issue by brunetton** [Ulauncher/ulauncher-kill#9]
Hi, probably a stupid question but: 

Based on README's screenshots it seems that it's possible to choose another signal to send to the process: 
   <img aligh="center" src="http://i.imgur.com/DT7Ymz4.png">
   How to achieve this ? The only thing I can see is typing `kill ` then the process name; but at any moment I'm asked for the signame to send

Did I missed something ?

Thanks

**Comment by gornostal** [comment]
To choose a signal you first select a process using the arrow keys, then press `Alt+Enter`
Please reopen if you have any other questions.

**Comment by brunetton** [comment]
Thanks !
